# Generated by Django 3.1.1 on 2020-09-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0002_auto_20200904_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='vendor_url',
            field=models.URLField(blank=True, help_text='Vendor / website URL to buy more', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hours_to_make',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='target_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
