# Generated by Django 3.1.1 on 2020-09-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0004_auto_20200904_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
