# Generated by Django 3.1.1 on 2020-09-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0005_product_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='sku',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
