# Generated by Django 3.1.1 on 2020-09-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0011_auto_20200905_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
