# Generated by Django 3.1.1 on 2020-09-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0012_auto_20200924_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
