# Generated by Django 3.1.1 on 2020-09-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0014_auto_20200924_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='vendor_url',
            new_name='source',
        ),
    ]
